services:
  mmaction2:
  # Start instructions: xhost local:root && docker run -it --rm -e SDL_VIDEODRIVER=x11 -e DISPLAY=$DISPLAY --env='DISPLAY' --gpus all --ipc host --privileged --network host -p 8080:8081 -v /tmp/.X11-unix:/tmp/.X11-unix:rw -v file_locations:/storage -v /weights:/weights openpcdet:cuda11 xfce4-terminal --title=openPCDet
    image: kingszun/mmaction
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    # network_mode: host
    privileged: true
    env_file:
      - .env
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../data:/data
      - ../:/Project/mmaction2
    ports:
      - 8888:8888/tcp
      - 8080:8081/tcp
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
